plugins {
    id 'com.android.application'
}

android {
    namespace 'vn.caobang.weather'
    compileSdk 35

    defaultConfig {
        applicationId 'vn.caobang.weather'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }

    sourceSets {
        main {
            assets.srcDirs = ['../web']
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
